### ISSUE TITLE
CustomItems compatibility

### ISSUE THREAD

**Issue by benfiratkaya** [BenWoodworth/FastCraft#195]
## Description

Do you add CustomItems compatibility?

https://www.spigotmc.org/resources/%E2%9B%8F-custom-items-%E2%9C%85-1-8-1-17-%E2%9C%85-make-new-items-blocks-with-new-textures-recipes-triggers-more.63848/
## Server Details
- Server: 
- FastCraft: v3.?

**Comment by BenWoodworth** [comment]
Could you share what's not working right? Maybe giving a config that I can test with

**Comment by benfiratkaya** [comment]
Not showing CustomItems crafts in FastCraft menu. I can crafting in CraftingTable menu but I can't see in FastCraft menu.

**Comment by BenWoodworth** [comment]
Okay! Can you give me a CustomItems config I can use?

**Comment by benfiratkaya** [comment]
Recipe system:
```
recipes:
- shape:
  - bbx
  - bcx
  - xcx
  shaped: true
  items:
  - item: platinum
    amount: 1
    allowDamaged: false
    key: b
  - item: minecraft:IRON_INGOT
    amount: 1
    allowDamaged: false
    key: c

```
